import SwiftUI
import SwiftData

struct SettingsView: View {
    @Bindable var selectedTopics: SelectedTopics
    @Environment(\.modelContext) private var modelContext

    @State private var notificationTime = Date.now
    @State private var aiStatus: AIGenerationStatus = .checking
    @AppStorage("summaryEngine") private var engineRaw = SummaryEngine.automatic.rawValue
    @ObservedObject private var gemma = GemmaModelManager.shared

    var body: some View {
        NavigationStack {
            Form {
                Section("Topics") {
                    NavigationLink {
                        TopicPickerView(selectedTopics: selectedTopics)
                            .navigationTitle("Topics")
                    } label: {
                        HStack {
                            Text("Selected topics")
                            Spacer()
                            Text("\(selectedTopics.categoryIDs.count)")
                                .foregroundStyle(.secondary)
                        }
                    }
                }

                Section("Daily notification") {
                    Toggle("Morning digest alert", isOn: $selectedTopics.notificationsEnabled)
                        .onChange(of: selectedTopics.notificationsEnabled) { _, enabled in
                            save()
                            if enabled {
                                Task {
                                    await NotificationManager.shared.requestAuthorization()
                                    BackgroundRefreshManager.schedule(
                                        hour: selectedTopics.notificationHour,
                                        minute: selectedTopics.notificationMinute
                                    )
                                }
                            }
                        }

                    DatePicker("Time", selection: $notificationTime, displayedComponents: .hourAndMinute)
                        .onChange(of: notificationTime) { _, newValue in
                            let comps = Calendar.current.dateComponents([.hour, .minute], from: newValue)
                            selectedTopics.notificationHour = comps.hour ?? 8
                            selectedTopics.notificationMinute = comps.minute ?? 0
                            save()
                            BackgroundRefreshManager.schedule(
                                hour: selectedTopics.notificationHour,
                                minute: selectedTopics.notificationMinute
                            )
                        }
                        .disabled(!selectedTopics.notificationsEnabled)
                }

                Section("Appearance") {
                    Picker("Theme", selection: $selectedTopics.appearance) {
                        ForEach(AppAppearance.allCases) { appearance in
                            Text(appearance.displayName).tag(appearance)
                        }
                    }
                    .pickerStyle(.segmented)
                    .onChange(of: selectedTopics.appearance) { save() }
                }

                Section("Summaries") {
                    Picker("Engine", selection: engineBinding) {
                        ForEach(SummaryEngine.allCases) { engine in
                            Text(engine.displayName).tag(engine)
                        }
                    }

                    HStack {
                        Label("Status", systemImage: "sparkles")
                        Spacer()
                        switch aiStatus {
                        case .checking:
                            ProgressView()
                        case .working(let provider):
                            Text(provider.displayName).foregroundStyle(.green)
                        case .failing, .unavailable:
                            Text("Off").foregroundStyle(.secondary)
                        }
                    }
                    if let detail = aiStatusDetail {
                        Text(detail)
                            .font(.footnote)
                            .foregroundStyle(.secondary)
                    }
                    if case .working(.gemini) = aiStatus {
                        Text("Summaries are generated by Google Gemini; paper titles and abstracts are sent to Google.")
                            .font(.footnote)
                            .foregroundStyle(.secondary)
                    }
                    if case .working(.gemma) = aiStatus {
                        Text("Runs fully on your device; nothing is sent anywhere.")
                            .font(.footnote)
                            .foregroundStyle(.secondary)
                    }

                    gemmaModelRow
                }
            }
            .navigationTitle("Settings")
            .task {
                aiStatus = await SummaryService.shared.probeGeneration()
            }
            .onChange(of: engineRaw) {
                Task { aiStatus = await SummaryService.shared.probeGeneration() }
            }
            .onAppear {
                notificationTime = Calendar.current.date(
                    bySettingHour: selectedTopics.notificationHour,
                    minute: selectedTopics.notificationMinute,
                    second: 0,
                    of: .now
                ) ?? .now
            }
        }
    }

    private var engineBinding: Binding<SummaryEngine> {
        Binding(
            get: { SummaryEngine(rawValue: engineRaw) ?? .automatic },
            set: { engineRaw = $0.rawValue }
        )
    }

    /// On-device Gemma model state + download controls.
    @ViewBuilder
    private var gemmaModelRow: some View {
        switch gemma.state {
        case .unavailable:
            Label("On-device Gemma needs the MLX package and a physical device.", systemImage: "iphone.slash")
                .font(.footnote)
                .foregroundStyle(.secondary)
        case .notDownloaded:
            Button {
                Task { await gemma.prepare() }
            } label: {
                Label("Download \(GemmaConfig.displayName) (\(GemmaConfig.approxDownloadSize))", systemImage: "arrow.down.circle")
            }
        case .downloading(let progress):
            VStack(alignment: .leading, spacing: 4) {
                Text("Downloading \(GemmaConfig.displayName)… \(Int(progress * 100))%")
                    .font(.footnote)
                ProgressView(value: progress)
            }
        case .ready:
            HStack {
                Label("\(GemmaConfig.displayName) ready", systemImage: "checkmark.circle.fill")
                    .foregroundStyle(.green)
                Spacer()
                Button("Delete", role: .destructive) { gemma.delete() }
                    .font(.footnote)
            }
        case .failed(let message):
            VStack(alignment: .leading, spacing: 4) {
                Text(message).font(.footnote).foregroundStyle(.red)
                Button("Retry") { Task { await gemma.prepare() } }
                    .font(.footnote)
            }
        }
    }

    private var aiStatusDetail: String? {
        switch aiStatus {
        case .checking, .working: return nil
        case .failing(let reason): return reason
        case .unavailable(let reason): return reason
        }
    }

    private func save() {
        try? modelContext.save()
    }
}
